/*
 * Pipeline: function-a
 */

pipeline{
    agent any
    parameters{
      string(name: 'project', defaultValue:'functions/function-a', description: 'Path of project')
    }
    stages{
      stage("Validating Changes"){
        when{
          expression { BRANCH_NAME ==~ /^(?:(?!prod).)*$/ }
        }
        steps{
          echo "Branch is different than prod"
        }
      }
      stage("Build Job"){
        when{
          expression { BRANCH_NAME ==~ /^(?:(?!prod).)*$/ }
        }
        steps{
          sh "chmod +x ${env.WORKSPACE}/${params.project}/build.sh"
          sh "${env.WORKSPACE}/${params.project}/build.sh"
        }
      }
    }
}
