/*
 * Pipeline: provision-b
 */

pipeline{
    agent any
    parameters{
      string(name: 'project', defaultValue:'infrastructure/provision-b', description: 'Path of project')
    }
    stages{
      stage("Validating Changes"){
        when{
          expression { BRANCH_NAME ==~ /^(?:(?!prod).)*$/ }
        }
        steps{
          echo "Branch is different than prod"
        }
      }
      stage("Build Job"){
        when{
          expression { BRANCH_NAME ==~ /^(?:(?!prod).)*$/ }
        }
        steps{
          sh "chmod +x ${env.WORKSPACE}/${params.project}/build.sh"
          sh "${env.WORKSPACE}/${params.project}/build.sh"
        }
      }
      stage("Launching Next Jobs"){
        when{
          expression { BRANCH_NAME ==~ /^(?:(?!prod).)*$/ }
        }
        steps{
          parallel(
            stage("Launching Fn A"){
              steps{
                echo "#########################"
                echo "### Launching FUNCTION-A"
                echo "#########################"
                build "../../functions/function-a/${env.BRANCH_NAME}"
              }
            }
            stage("Launching Fn B"){
              steps{
                echo "#########################"
                echo "### Launching FUNCTION-B"
                echo "#########################"
                build "../../functions/function-b/${env.BRANCH_NAME}"
              }
            }
          )
          
        }
      }
    }
}
