/*
 * Pipeline: provision-a
 */

pipeline{
    agent any
    parameters{
      string(name: 'project', defaultValue:'infrastructure/provision-a', description: 'Path of project')
    }
    stages{
      stage("Validating Changes"){
        when{
          expression { BRANCH_NAME ==~ /^(?:(?!prod).)*$/ }
        }
        steps{
          echo "Branch is different than prod"
        }
      }
      stage("Build Job"){
        steps{
          sh "chmod +x ${env.WORKSPACE}/${params.project}/build.sh"
          sh "${env.WORKSPACE}/${params.project}/build.sh"
        }
      }
    }
    post{
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
